<a href="https://colab.research.google.com/github/jmorral/nyu-python-public-policy/blob/master/HW3_with_actual_boolean_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data_hw3.csv', header='infer')

In [0]:
df['descriptor'] = df['descriptor'].str.lower() 
df['complaint_type'] = df['complaint_type'].str.lower()

Q1: Create a function that checks each row in the 311 dataframe to see if the word "graffiti" is present in either the complaint_type value or descriptor value. Both columns may contain the word, so you should check both. If the word "graffiti" is found, the function should return the boolean value True. If "graffiti" is not found, the function should return the boolean value False.

In [0]:
def graffiti_counts(row):
  if pd.notnull(row.descriptor):  
    if 'graffiti' in row.complaint_type and row.complaint_type != 'NaN':
      return True
    elif 'graffiti' in row.descriptor and row.descriptor != 'NaN':
      return True
    else:
      return False

In [0]:
def graffiti_counts_py(row):
#Tried it a second time with nested IF statements before searching for 'graffiti'. Used above function for the rest of the assignment though. 
  if pd.notnull(row.descriptor):  
    if row.complaint_type != 'NaN':
      if row.descriptor != 'NaN':
        if 'graffiti' in row.complaint_type:
          return True
        elif 'graffiti' in row.descriptor:
          return True
        else:
          return False

Q2: Apply the function created in Step 1 to the 311 dataframe and create a new column called graffiti_flag that captures the output from the function.

In [9]:
df['graffiti_flag'] = df.apply(graffiti_counts, axis=1)
df.head(10)

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has com...,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have suf...,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)",False
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,maintenance or facility,hours of operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has com...,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has com...,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determi...,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,661,661,39895587,08/01/2018 07:34:44 AM,08/10/2018 01:45:07 PM,DPR,Department of Parks and Recreation,maintenance or facility,unsecured facility,Park,10033.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/04/2018 07:34:44 AM,The Department of Parks and Recreation has com...,08/10/2018 01:44:53 PM,12 MANHATTAN,NaN,MANHATTAN,NaN,NaN,PHONE,Fort Tryon Park - Anne Loftus Playground,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
6,713,713,39890857,08/01/2018 07:53:38 AM,08/08/2018 04:21:55 PM,DPR,Department of Parks and Recreation,maintenance or facility,grass/weeds,Street/Curbside,11429.0,211 STREET,211 STREET,104 AVENUE,HOLLIS AVENUE,NaN,NaN,BLOCKFACE,QUEENS VILLAGE,NaN,NaN,Closed,08/15/2018 07:53:38 AM,The Service Request submitted did not have suf...,08/08/2018 04:21:55 PM,13 QUEENS,NaN,QUEENS,1054213.0,198447.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.711091,-73.747639,"(40.711091308732435, -73.74763946439865)",False
7,789,789,39894929,08/01/2018 08:07:49 AM,08/07/2018 12:20:24 PM,DOT,Department of Transportation,broken parking meter,coin or card did not register,Street,10461.0,NaN,NaN,NaN,NaN,WESTCHESTER AVENUE,COLONIAL AVENUE,INTERSECTION,BRONX,NaN,NaN,Closed,08/21/2018 08:07:49 AM,General maintenance and cleaning is on a regul...,08/07/2018 12:20:24 PM,10 BRONX,NaN,BRONX,1031884.0,249950.0,PHONE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.852601,-73.827816,"(40.852601460220185, -73.82781602326443)",False
8,860,860,39897352,08/01/2018 08:21:08 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,NaN,NaN,141 141 ST,141 ST,NaN,NaN,NaN,NaN,ADDRESS,NaN,NaN,NaN,Open,NaN,NaN,08/01/2018 08:21:08 AM,Unspecified QUEENS,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,876,876,39891938,08/01/2018 08:24:41 AM,08/30/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,237 IRVING AVENUE,IRVING AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,04 BROOKLYN,3.032900e+09,BROOKLYN,1007216.0,194542.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700620,-73.917173,"(40.70061981717157, -73.91717344071574)",True

Q2 Test:

In [10]:
graffiti_flag_test = df.groupby('graffiti_flag').size()
graffiti_flag_test

graffiti_flag
False    38206
True     26371
dtype: int64

In [11]:
## Fixing because there are actually booleans now
graffiti_subset = df[['complaint_type', 'descriptor', 'graffiti_flag']]
graffiti_subset_true = graffiti_subset[graffiti_subset.graffiti_flag == True]
graffiti_subset_true.groupby('complaint_type').size()

complaint_type
bridge condition                 60
broken parking meter             83
bus stop shelter complaint      187
graffiti                      24986
highway condition               310
maintenance or facility         577
public payphone complaint       112
public toilet                    10
school maintenance               46
dtype: int64

In [12]:
## Doing again now with booleans. I think I was just comparing the two different ways of generating this. Same results for each. 
df_graffiti = df[df.graffiti_flag == True]
df_graffiti.groupby('complaint_type').size()

complaint_type
bridge condition                 60
broken parking meter             83
bus stop shelter complaint      187
graffiti                      24986
highway condition               310
maintenance or facility         577
public payphone complaint       112
public toilet                    10
school maintenance               46
dtype: int64

Q3: Create another dataframe df_graffiti that only contains records where graffiti_flag is True. df_graffiti = df[df.graffiti_flag]

In [13]:
df_graffiti = df[df.graffiti_flag == True]
df_graffiti.head(10)

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
8,860,860,39897352,08/01/2018 08:21:08 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,NaN,NaN,141 141 ST,141 ST,NaN,NaN,NaN,NaN,ADDRESS,NaN,NaN,NaN,Open,NaN,NaN,08/01/2018 08:21:08 AM,Unspecified QUEENS,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,876,876,39891938,08/01/2018 08:24:41 AM,08/30/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,237 IRVING AVENUE,IRVING AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,04 BROOKLYN,3.032900e+09,BROOKLYN,1007216.0,194542.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700620,-73.917173,"(40.70061981717157, -73.91717344071574)",True
10,964,964,39897349,08/01/2018 08:40:34 AM,08/23/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,10467.0,345 EAST 205 STREET,EAST 205 STREET,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BRONX,2.033500e+09,BRONX,1018509.0,257554.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.873534,-73.876124,"(40.87353414980636, -73.87612406980227)",True
12,1007,1007,39893314,08/01/2018 08:47:45 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11220.0,5506 5 AVENUE,5 AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BROOKLYN,3.008310e+09,BROOKLYN,980544.0,173249.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642204,-74.013354,"(40.64220432954161, -74.01335393443593)",True
13,1013,1013,39897422,08/01/2018 08:49:15 AM,08/28/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,884 HART STREET,HART STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.032360e+09,BROOKLYN,1005915.0,195340.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.702813,-73.921863,"(40.70281342017164, -73.92186290937498)",True
15,1113,1113,39890371,08/01/2018 09:05:14 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11222.0,39 NORTH HENRY STREET,NORTH HENRY STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,01 BROOKLYN,3.028270e+09,BROOKLYN,1000125.0,201791.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720532,-73.942730,"(40.720532158642264, -73.94272993232262)",True
16,1125,1125,39890363,08/01/2018 09:06:03 AM,10/03/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11222.0,37 NORTH HENRY STREET,NORTH HENRY STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/23/2018 02:36:05 PM,01 BROOKLYN,3.028278e+09,BROOKLYN,1000129.0,201759.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720444,-73.942716,"(40.72044431919613, -73.94271557756703)",True
21,1361,1361,39897421,08/01/2018 09:34:51 AM,08/27/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11207.0,830 KNICKERBOCKER AVENUE,KNICKERBOCKER AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.034240e+09,BROOKLYN,1010201.0,191407.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692007,-73.906420,"(40.692006725226506, -73.90642016600616)",True
22,1379,1379,39894550,08/01/2018 09:37:09 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11233.0,663 MACDONOUGH STREET,MACDONOUGH STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,"The cleaning crew was dispatched, but the owne...",10/03/2018 01:02:01 PM,03 BROOKLYN,3.014970e+09,BROOKLYN,1006583.0,188415.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683804,-73.919477,"(40.68380424457166, -73.91947665760173)",True
23,1383,1383,39898718,08/01/2018 09:37:50 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11233.0,661 MACDONOUGH STREET,MACDONOUGH STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/03/2018 01:02:01 PM,03 BROOKLYN,3.014970e+09,BROOKLYN,1006568.0,188413.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683799,-73.919531,"(40.6837987928642, -73.9195307478448)",True

Q4: Group your dataframe df_graffiti to get the count of requests per community_board. Use .nlargest() to identify which Community District has the highest count.

In [0]:
df_graffiti.groupby('community_board').size().nlargest().reset_index(name='count')

  community_board  count
0     01 BROOKLYN   1797
1    03 MANHATTAN   1593
2     04 BROOKLYN   1429
3     03 BROOKLYN   1252
4     05 BROOKLYN    962

A4: Brooklyn 01 has the highest count of requests.